[
    {
        "name":"fantam animals",
        "250":{
            "type":"ERC721",
            "nft":"",
            "gateway":""
        },
        "1":{
            "type":"ERC721",
            "nft":"",
            "gateway":""
        },
        "43114":{
            "type":"ERC721",
            "nft":"",
            "gateway":""
        }
    }
]